ifeq ($(MKNBLIBS),1)
all: $(TARGET)
$(ELF): $(TARGET)
endif

ifeq ($(NBDEBUG),1)
$(TARGET): $(DBLIB_OBJ_FILES)
else
$(TARGET): $(LIB_OBJ_FILES)
endif
	$(RM) $@
	$(AR) cr $@ $^

.PHONY: clean-nblibs load-nbimage

clean-nblibs:
	$(RM) $(OBJDIR)

load-nbimage:
	$(APPUPDATE) $(NBIMAGE) $(DEVIP)

htmldata.cpp: $(COMPHTML_SRCS)
	comphtml $(HTMLDIR) -o$@

htmldata.o: htmldata.cpp
	$(CXX) -c -I"../src" $(CXXFLAGS) $(CPPFLAGS) $< -o $@

ifneq ($(wildcard $(OBJDIR)/.stale),)
clean: clean-nblibs
endif
